services:
  - type: web
    name: movieapp-backend
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: movieapp-db
          property: connectionString
      - key: TMDB_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/health

databases:
  - name: movieapp-db
    databaseName: movieapp
    user: movieapp_user